export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS'
export const LOAD_CATEGORIES_FAIL = 'LOAD_CATEGORIES_FAIL'


export const LOAD_CHANNEL_SUCCESS = 'LOAD_CHANNEL_SUCCESS'
export const LOAD_CHANNEL_FAIL = 'LOAD_CHANNEL_FAIL'




export const LOAD_EPISODE_SUCCESS = 'LOAD_EPISODE_SUCCESS'
export const LOAD_EPISODE_FAIL= 'LOAD_EPISODE_FAIL'